apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
spec:
  template:
    metadata:
      name: nginx-alpine
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
  replicas: 2 
  selector:
    matchLabels:
      app: nginx-app



